// Auto-generated by scripts/build-gallery-from-sheet.js — do not edit manually.
// Source: https://docs.google.com/spreadsheets/d/1198Q00DPa5Rsk2atWGEDBzxD53f4-pmLdrbu8tUVzFw
// Generated: 2026-05-12T20:17:54.721Z

export const GALLERY_IMAGES = [
  {
    "id": "1PpxhA81OqmT_yL3ky7UUrD5_GoCIKxO8",
    "sno": "1",
    "theme": "Exterior",
    "country": "Canada",
    "state": "Ontario",
    "city": "Ottawa",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Agampreet - Concept Designs",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [
      "Auto CAD",
      "Lumion",
      "SketchUp",
      "Photoshop"
    ],
    "description": "Project: Classical Residencial Villa",
    "driveLink": "https://drive.google.com/file/d/1PpxhA81OqmT_yL3ky7UUrD5_GoCIKxO8/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1PpxhA81OqmT_yL3ky7UUrD5_GoCIKxO8=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1PpxhA81OqmT_yL3ky7UUrD5_GoCIKxO8=w400"
  },
  {
    "id": "1j9HVhg2SwCVZCqP4pBjdw7nBBpBs8xGT",
    "sno": "2",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Pathankot",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Manjinder- Planet Design and associates",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Commercial outlet",
    "driveLink": "https://drive.google.com/file/d/1j9HVhg2SwCVZCqP4pBjdw7nBBpBs8xGT/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1j9HVhg2SwCVZCqP4pBjdw7nBBpBs8xGT=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1j9HVhg2SwCVZCqP4pBjdw7nBBpBs8xGT=w400"
  },
  {
    "id": "1mMBySbl9BG9Y2IfKxV4lt9YpsYISBYCA",
    "sno": "3",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Pathankot",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Manjinder- Planet Design and associates",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Commercial outlet",
    "driveLink": "https://drive.google.com/file/d/1mMBySbl9BG9Y2IfKxV4lt9YpsYISBYCA/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1mMBySbl9BG9Y2IfKxV4lt9YpsYISBYCA=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1mMBySbl9BG9Y2IfKxV4lt9YpsYISBYCA=w400"
  },
  {
    "id": "1Wow86cMLyz54OXEZG3iVZC-2svF_WJDZ",
    "sno": "4",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1Wow86cMLyz54OXEZG3iVZC-2svF_WJDZ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Wow86cMLyz54OXEZG3iVZC-2svF_WJDZ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Wow86cMLyz54OXEZG3iVZC-2svF_WJDZ=w400"
  },
  {
    "id": "1Skmz7GBbpJvmVgfU3PEy1JDm21GdoQRE",
    "sno": "5",
    "theme": "Exterior",
    "country": "India",
    "state": "Uttar Pradesh",
    "city": "Kanpur",
    "clientType": "Builders/Developer",
    "clientName": "Dream Hut",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Farmhouse",
    "driveLink": "https://drive.google.com/file/d/1Skmz7GBbpJvmVgfU3PEy1JDm21GdoQRE/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Skmz7GBbpJvmVgfU3PEy1JDm21GdoQRE=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Skmz7GBbpJvmVgfU3PEy1JDm21GdoQRE=w400"
  },
  {
    "id": "123QBooSYNOdaDlGXKnpDv1Nmgk3kH8hH",
    "sno": "6",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Classical jewellery showroom",
    "driveLink": "https://drive.google.com/file/d/123QBooSYNOdaDlGXKnpDv1Nmgk3kH8hH/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/123QBooSYNOdaDlGXKnpDv1Nmgk3kH8hH=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/123QBooSYNOdaDlGXKnpDv1Nmgk3kH8hH=w400"
  },
  {
    "id": "1cYnMN8iWcTQO4KgGWzeDRQRojNT4xoXf",
    "sno": "7",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1cYnMN8iWcTQO4KgGWzeDRQRojNT4xoXf/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1cYnMN8iWcTQO4KgGWzeDRQRojNT4xoXf=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1cYnMN8iWcTQO4KgGWzeDRQRojNT4xoXf=w400"
  },
  {
    "id": "1Xj9fNWlG5R6i6lNxEebeuqbHrTsSvuxN",
    "sno": "8",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Classical Residencial House",
    "driveLink": "https://drive.google.com/file/d/1Xj9fNWlG5R6i6lNxEebeuqbHrTsSvuxN/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Xj9fNWlG5R6i6lNxEebeuqbHrTsSvuxN=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Xj9fNWlG5R6i6lNxEebeuqbHrTsSvuxN=w400"
  },
  {
    "id": "1APBR9B_S-bSbvdA2jfDrI5QrzJ2EkBbi",
    "sno": "9",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Mohali",
    "clientType": "Architectural Firm",
    "clientName": "Design Anthem Forum",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1APBR9B_S-bSbvdA2jfDrI5QrzJ2EkBbi/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1APBR9B_S-bSbvdA2jfDrI5QrzJ2EkBbi=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1APBR9B_S-bSbvdA2jfDrI5QrzJ2EkBbi=w400"
  },
  {
    "id": "1sgk6i72Iu8429YdmJJqIuKIcp1Oef2hn",
    "sno": "10",
    "theme": "Exterior",
    "country": "India",
    "state": "Manipur",
    "city": "Churachandpur",
    "clientType": "Architectural Firm",
    "clientName": "LZ_Designs",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Classical Commercial building",
    "driveLink": "https://drive.google.com/file/d/1sgk6i72Iu8429YdmJJqIuKIcp1Oef2hn/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1sgk6i72Iu8429YdmJJqIuKIcp1Oef2hn=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1sgk6i72Iu8429YdmJJqIuKIcp1Oef2hn=w400"
  },
  {
    "id": "1HaI_dqCVqheMfBKLI3jhqZ1DVJIA9xYs",
    "sno": "11",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1HaI_dqCVqheMfBKLI3jhqZ1DVJIA9xYs/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1HaI_dqCVqheMfBKLI3jhqZ1DVJIA9xYs=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1HaI_dqCVqheMfBKLI3jhqZ1DVJIA9xYs=w400"
  },
  {
    "id": "14XQts_DvQ1onoZXMje4oxG5yuxIIw9YP",
    "sno": "12",
    "theme": "Exterior",
    "country": "Canada",
    "state": "Ontario",
    "city": "Ottawa",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Agampreet - Concept Designs",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Classical Residencial Villa",
    "driveLink": "https://drive.google.com/file/d/14XQts_DvQ1onoZXMje4oxG5yuxIIw9YP/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/14XQts_DvQ1onoZXMje4oxG5yuxIIw9YP=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/14XQts_DvQ1onoZXMje4oxG5yuxIIw9YP=w400"
  },
  {
    "id": "1qnHeoW_39U7mcVatrMCx7-_nM71FWSB4",
    "sno": "13",
    "theme": "Exterior",
    "country": "India",
    "state": "Himachal Pradesh",
    "city": "Dalhousie",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Resort",
    "driveLink": "https://drive.google.com/file/d/1qnHeoW_39U7mcVatrMCx7-_nM71FWSB4/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1qnHeoW_39U7mcVatrMCx7-_nM71FWSB4=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1qnHeoW_39U7mcVatrMCx7-_nM71FWSB4=w400"
  },
  {
    "id": "11X-cWVKTDB1sQ-2faxb21KsnhBl_Hlav",
    "sno": "14",
    "theme": "Exterior",
    "country": "India",
    "state": "Delhi",
    "city": null,
    "clientType": "Builders/Developer",
    "clientName": "Mr.Raman- EDC Architects",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Modern Commercial building",
    "driveLink": "https://drive.google.com/file/d/11X-cWVKTDB1sQ-2faxb21KsnhBl_Hlav/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/11X-cWVKTDB1sQ-2faxb21KsnhBl_Hlav=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/11X-cWVKTDB1sQ-2faxb21KsnhBl_Hlav=w400"
  },
  {
    "id": "1jggF-5w_I7xaP9_S1LFdHEXnwmvCkYmj",
    "sno": "15",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Primary School",
    "driveLink": "https://drive.google.com/file/d/1jggF-5w_I7xaP9_S1LFdHEXnwmvCkYmj/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1jggF-5w_I7xaP9_S1LFdHEXnwmvCkYmj=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1jggF-5w_I7xaP9_S1LFdHEXnwmvCkYmj=w400"
  },
  {
    "id": "1lFW1Bn-T1u69VAMGcn6iB2RFQifmg2Jx",
    "sno": "16",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1lFW1Bn-T1u69VAMGcn6iB2RFQifmg2Jx/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1lFW1Bn-T1u69VAMGcn6iB2RFQifmg2Jx=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1lFW1Bn-T1u69VAMGcn6iB2RFQifmg2Jx=w400"
  },
  {
    "id": "183I9GA-_q5NWvgTP9DKmp603nayg07Sm",
    "sno": "17",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Classical Residencial House",
    "driveLink": "https://drive.google.com/file/d/183I9GA-_q5NWvgTP9DKmp603nayg07Sm/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/183I9GA-_q5NWvgTP9DKmp603nayg07Sm=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/183I9GA-_q5NWvgTP9DKmp603nayg07Sm=w400"
  },
  {
    "id": "1H_KsTOeqG2ImUJ_6IEvue6Dp_eHEI8-X",
    "sno": "18",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Radha Krishna Temple",
    "driveLink": "https://drive.google.com/file/d/1H_KsTOeqG2ImUJ_6IEvue6Dp_eHEI8-X/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1H_KsTOeqG2ImUJ_6IEvue6Dp_eHEI8-X=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1H_KsTOeqG2ImUJ_6IEvue6Dp_eHEI8-X=w400"
  },
  {
    "id": "1sJJmeSj3CouF9161yIJApf2SuBaxw4HG",
    "sno": "19",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Modern Farmhouse",
    "driveLink": "https://drive.google.com/file/d/1sJJmeSj3CouF9161yIJApf2SuBaxw4HG/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1sJJmeSj3CouF9161yIJApf2SuBaxw4HG=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1sJJmeSj3CouF9161yIJApf2SuBaxw4HG=w400"
  },
  {
    "id": "1MTvcBQykHpDTB5Q2GT1e99vqlvCJv4QP",
    "sno": "20",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1MTvcBQykHpDTB5Q2GT1e99vqlvCJv4QP/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1MTvcBQykHpDTB5Q2GT1e99vqlvCJv4QP=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1MTvcBQykHpDTB5Q2GT1e99vqlvCJv4QP=w400"
  },
  {
    "id": "11Enu3IB1vFEJC0F3WezQxI1qSZuzxF7V",
    "sno": "21",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/11Enu3IB1vFEJC0F3WezQxI1qSZuzxF7V/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/11Enu3IB1vFEJC0F3WezQxI1qSZuzxF7V=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/11Enu3IB1vFEJC0F3WezQxI1qSZuzxF7V=w400"
  },
  {
    "id": "1aN-JC7v8GVFI8WAedIWOuKQ2998WeAUX",
    "sno": "22",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1aN-JC7v8GVFI8WAedIWOuKQ2998WeAUX/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1aN-JC7v8GVFI8WAedIWOuKQ2998WeAUX=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1aN-JC7v8GVFI8WAedIWOuKQ2998WeAUX=w400"
  },
  {
    "id": "1ugumVgkIhj-iAzzXwMlY7RumC-E_vJBr",
    "sno": "23",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1ugumVgkIhj-iAzzXwMlY7RumC-E_vJBr/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1ugumVgkIhj-iAzzXwMlY7RumC-E_vJBr=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1ugumVgkIhj-iAzzXwMlY7RumC-E_vJBr=w400"
  },
  {
    "id": "1R4d-JS1nv3xViBDg_00ZtuApduLi1ZmM",
    "sno": "24",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1R4d-JS1nv3xViBDg_00ZtuApduLi1ZmM/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1R4d-JS1nv3xViBDg_00ZtuApduLi1ZmM=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1R4d-JS1nv3xViBDg_00ZtuApduLi1ZmM=w400"
  },
  {
    "id": "1FZ89M9FfhEEjCcMBy2-RKkPdcte8AT53",
    "sno": "25",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Kaushik",
    "services": [
      "Exterior 3D Rendering",
      "Elevation Design"
    ],
    "software": [],
    "description": "Project: Modern Residential house",
    "driveLink": "https://drive.google.com/file/d/1FZ89M9FfhEEjCcMBy2-RKkPdcte8AT53/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1FZ89M9FfhEEjCcMBy2-RKkPdcte8AT53=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1FZ89M9FfhEEjCcMBy2-RKkPdcte8AT53=w400"
  },
  {
    "id": "12Tg68cfvXj4CYGrA8sffu6OGJg46SCZr",
    "sno": "26",
    "theme": "Exterior",
    "country": "India",
    "state": "Delhi",
    "city": null,
    "clientType": "Builders/Developer",
    "clientName": "Mr.Raman- EDC Architects",
    "services": [],
    "software": [],
    "description": "Project: Modern Commercial building",
    "driveLink": "https://drive.google.com/file/d/12Tg68cfvXj4CYGrA8sffu6OGJg46SCZr/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/12Tg68cfvXj4CYGrA8sffu6OGJg46SCZr=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/12Tg68cfvXj4CYGrA8sffu6OGJg46SCZr=w400"
  },
  {
    "id": "1e8fT5hSoBaDtgQLKBvJVTQo2cqFWjETN",
    "sno": "27",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Ludhiana",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Manjinder- Planet Design and associates",
    "services": [
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Commercial outlet",
    "driveLink": "https://drive.google.com/file/d/1e8fT5hSoBaDtgQLKBvJVTQo2cqFWjETN/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1e8fT5hSoBaDtgQLKBvJVTQo2cqFWjETN=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1e8fT5hSoBaDtgQLKBvJVTQo2cqFWjETN=w400"
  },
  {
    "id": "1P8hOF2rMgfaBXMP5twA_unCS1uQP0MM4",
    "sno": "29",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Akash Bhutani",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Kids Bedroom",
    "driveLink": "https://drive.google.com/file/d/1P8hOF2rMgfaBXMP5twA_unCS1uQP0MM4/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1P8hOF2rMgfaBXMP5twA_unCS1uQP0MM4=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1P8hOF2rMgfaBXMP5twA_unCS1uQP0MM4=w400"
  },
  {
    "id": "17S5hsARFXpl0mKo_6C10bdM2k5TRuthJ",
    "sno": "30",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Lovepreet",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Drawing Room",
    "driveLink": "https://drive.google.com/file/d/17S5hsARFXpl0mKo_6C10bdM2k5TRuthJ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/17S5hsARFXpl0mKo_6C10bdM2k5TRuthJ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/17S5hsARFXpl0mKo_6C10bdM2k5TRuthJ=w400"
  },
  {
    "id": "1NNyX4-4C_PZd9gnx6luBkHxnqzU8nl7K",
    "sno": "31",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Sagarika",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Cafe",
    "driveLink": "https://drive.google.com/file/d/1NNyX4-4C_PZd9gnx6luBkHxnqzU8nl7K/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1NNyX4-4C_PZd9gnx6luBkHxnqzU8nl7K=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1NNyX4-4C_PZd9gnx6luBkHxnqzU8nl7K=w400"
  },
  {
    "id": "1aBcaF9OTygggq61myhahb2wUccr4sT1y",
    "sno": "32",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Interior Designers",
    "clientName": "Mr.Jatin Narula - Kitchen Decor",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Kitchen",
    "driveLink": "https://drive.google.com/file/d/1aBcaF9OTygggq61myhahb2wUccr4sT1y/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1aBcaF9OTygggq61myhahb2wUccr4sT1y=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1aBcaF9OTygggq61myhahb2wUccr4sT1y=w400"
  },
  {
    "id": "1sfvZloO7zPUAevTn2p-WCTvHrcS8jFGP",
    "sno": "33",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Interior Designers",
    "clientName": "Mr.Jatin Narula - Kitchen Decor",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Walk in Closet",
    "driveLink": "https://drive.google.com/file/d/1sfvZloO7zPUAevTn2p-WCTvHrcS8jFGP/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1sfvZloO7zPUAevTn2p-WCTvHrcS8jFGP=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1sfvZloO7zPUAevTn2p-WCTvHrcS8jFGP=w400"
  },
  {
    "id": "1BDhp7TlI3CVQaWj6WphN1nnDltgUSzDo",
    "sno": "34",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Interior Designers",
    "clientName": "Mr.Jatin Narula - Kitchen Decor",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Kitchen",
    "driveLink": "https://drive.google.com/file/d/1BDhp7TlI3CVQaWj6WphN1nnDltgUSzDo/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1BDhp7TlI3CVQaWj6WphN1nnDltgUSzDo=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1BDhp7TlI3CVQaWj6WphN1nnDltgUSzDo=w400"
  },
  {
    "id": "1p9W3AyGMdi6qfn3O4_eOATHfqKnAJkbN",
    "sno": "35",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Waiting area",
    "driveLink": "https://drive.google.com/file/d/1p9W3AyGMdi6qfn3O4_eOATHfqKnAJkbN/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1p9W3AyGMdi6qfn3O4_eOATHfqKnAJkbN=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1p9W3AyGMdi6qfn3O4_eOATHfqKnAJkbN=w400"
  },
  {
    "id": "192d2TO7097AqlXdCeqvFmeuKF9m5WyTx",
    "sno": "36",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Bedroom",
    "driveLink": "https://drive.google.com/file/d/192d2TO7097AqlXdCeqvFmeuKF9m5WyTx/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/192d2TO7097AqlXdCeqvFmeuKF9m5WyTx=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/192d2TO7097AqlXdCeqvFmeuKF9m5WyTx=w400"
  },
  {
    "id": "1zrKUQg0YdmDgcGaj4lJtR6xV0335H8Qy",
    "sno": "37",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Drawing Room",
    "driveLink": "https://drive.google.com/file/d/1zrKUQg0YdmDgcGaj4lJtR6xV0335H8Qy/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1zrKUQg0YdmDgcGaj4lJtR6xV0335H8Qy=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1zrKUQg0YdmDgcGaj4lJtR6xV0335H8Qy=w400"
  },
  {
    "id": "1Wy5VeCs02T4K3Zl-HOFsaXjdl0SW_rgU",
    "sno": "38",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Bedroom",
    "driveLink": "https://drive.google.com/file/d/1Wy5VeCs02T4K3Zl-HOFsaXjdl0SW_rgU/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Wy5VeCs02T4K3Zl-HOFsaXjdl0SW_rgU=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Wy5VeCs02T4K3Zl-HOFsaXjdl0SW_rgU=w400"
  },
  {
    "id": "1WfBoR4VSOwoMYDdbYLVvKpJGqcDZFo10",
    "sno": "39",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior 3D rendering",
      "Interior Design"
    ],
    "software": [],
    "description": "Project: Bedroom",
    "driveLink": "https://drive.google.com/file/d/1WfBoR4VSOwoMYDdbYLVvKpJGqcDZFo10/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1WfBoR4VSOwoMYDdbYLVvKpJGqcDZFo10=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1WfBoR4VSOwoMYDdbYLVvKpJGqcDZFo10=w400"
  },
  {
    "id": "1uUmJAZRcMzVkjKVe4OkkOb0nvhGGkumr",
    "sno": "40",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Akash Bhutani",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Bedroom",
    "driveLink": "https://drive.google.com/file/d/1uUmJAZRcMzVkjKVe4OkkOb0nvhGGkumr/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1uUmJAZRcMzVkjKVe4OkkOb0nvhGGkumr=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1uUmJAZRcMzVkjKVe4OkkOb0nvhGGkumr=w400"
  },
  {
    "id": "1v27lFw8LVkiUudB0eMEwpbPKgf6ifgiB",
    "sno": "41",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Batala",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Ankit Bansal",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Office",
    "driveLink": "https://drive.google.com/file/d/1v27lFw8LVkiUudB0eMEwpbPKgf6ifgiB/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1v27lFw8LVkiUudB0eMEwpbPKgf6ifgiB=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1v27lFw8LVkiUudB0eMEwpbPKgf6ifgiB=w400"
  },
  {
    "id": "1QZjEeHWDLRWVTtt6I4GDk0xrlxsVcrIa",
    "sno": "42",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Batala",
    "clientType": "Individual Home Owner",
    "clientName": "Mr.Ankit Bansal",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Office",
    "driveLink": "https://drive.google.com/file/d/1QZjEeHWDLRWVTtt6I4GDk0xrlxsVcrIa/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1QZjEeHWDLRWVTtt6I4GDk0xrlxsVcrIa=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1QZjEeHWDLRWVTtt6I4GDk0xrlxsVcrIa=w400"
  },
  {
    "id": "1jN6-PaCqMaF19_jlJQObS7kZ_hMBGQiu",
    "sno": "52",
    "theme": "Plan",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Residential Plan",
    "driveLink": "https://drive.google.com/file/d/1jN6-PaCqMaF19_jlJQObS7kZ_hMBGQiu/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1jN6-PaCqMaF19_jlJQObS7kZ_hMBGQiu=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1jN6-PaCqMaF19_jlJQObS7kZ_hMBGQiu=w400"
  },
  {
    "id": "1HpV264pe9XppKx7UK45IbovASiYQV4KH",
    "sno": "53",
    "theme": "Plan",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1HpV264pe9XppKx7UK45IbovASiYQV4KH/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1HpV264pe9XppKx7UK45IbovASiYQV4KH=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1HpV264pe9XppKx7UK45IbovASiYQV4KH=w400"
  },
  {
    "id": "1k0Nm_o1tH4CQ5qGeg-3ZovYQw5sOwCVr",
    "sno": "54",
    "theme": "Plan",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Interior Design",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1k0Nm_o1tH4CQ5qGeg-3ZovYQw5sOwCVr/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1k0Nm_o1tH4CQ5qGeg-3ZovYQw5sOwCVr=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1k0Nm_o1tH4CQ5qGeg-3ZovYQw5sOwCVr=w400"
  },
  {
    "id": "10bOYEuxz49caqm2NrErVk09KAyeki204",
    "sno": "56",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Residencial House",
    "driveLink": "https://drive.google.com/file/d/10bOYEuxz49caqm2NrErVk09KAyeki204/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/10bOYEuxz49caqm2NrErVk09KAyeki204=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/10bOYEuxz49caqm2NrErVk09KAyeki204=w400"
  },
  {
    "id": "1FOIIiy_XKB0QMLDbf_nl33N5A-ZiV88G",
    "sno": "57",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1FOIIiy_XKB0QMLDbf_nl33N5A-ZiV88G/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1FOIIiy_XKB0QMLDbf_nl33N5A-ZiV88G=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1FOIIiy_XKB0QMLDbf_nl33N5A-ZiV88G=w400"
  },
  {
    "id": "1EBAaPtKQwKzB_P-BidDiFNkimIgjOENM",
    "sno": "58",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1EBAaPtKQwKzB_P-BidDiFNkimIgjOENM/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1EBAaPtKQwKzB_P-BidDiFNkimIgjOENM=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1EBAaPtKQwKzB_P-BidDiFNkimIgjOENM=w400"
  },
  {
    "id": "1dnu3gtNzoAzneankNspI83lTctHabV_m",
    "sno": "59",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1dnu3gtNzoAzneankNspI83lTctHabV_m/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1dnu3gtNzoAzneankNspI83lTctHabV_m=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1dnu3gtNzoAzneankNspI83lTctHabV_m=w400"
  },
  {
    "id": "1XEMrRpZCcbhlaNWyxNuHY1fGEwwpwiKJ",
    "sno": "60",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1XEMrRpZCcbhlaNWyxNuHY1fGEwwpwiKJ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1XEMrRpZCcbhlaNWyxNuHY1fGEwwpwiKJ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1XEMrRpZCcbhlaNWyxNuHY1fGEwwpwiKJ=w400"
  },
  {
    "id": "1utvi5j4wPhzm9hm-5sqzaGWjf6YnIfJt",
    "sno": "61",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1utvi5j4wPhzm9hm-5sqzaGWjf6YnIfJt/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1utvi5j4wPhzm9hm-5sqzaGWjf6YnIfJt=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1utvi5j4wPhzm9hm-5sqzaGWjf6YnIfJt=w400"
  },
  {
    "id": "1YpvkLO_PRlzRDw9Fl70B9E04i3crXsw7",
    "sno": "62",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1YpvkLO_PRlzRDw9Fl70B9E04i3crXsw7/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1YpvkLO_PRlzRDw9Fl70B9E04i3crXsw7=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1YpvkLO_PRlzRDw9Fl70B9E04i3crXsw7=w400"
  },
  {
    "id": "16aQHVjBXIZBUIh4u9nmDA86X_wJOgL4t",
    "sno": "63",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/16aQHVjBXIZBUIh4u9nmDA86X_wJOgL4t/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/16aQHVjBXIZBUIh4u9nmDA86X_wJOgL4t=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/16aQHVjBXIZBUIh4u9nmDA86X_wJOgL4t=w400"
  },
  {
    "id": "17BupMfI70GqcfIL4cUnWXwJHld5PXvis",
    "sno": "64",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/17BupMfI70GqcfIL4cUnWXwJHld5PXvis/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/17BupMfI70GqcfIL4cUnWXwJHld5PXvis=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/17BupMfI70GqcfIL4cUnWXwJHld5PXvis=w400"
  },
  {
    "id": "1mtXo-3QIMQorht3GSrHxBbg3GT1KXrFl",
    "sno": "65",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1mtXo-3QIMQorht3GSrHxBbg3GT1KXrFl/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1mtXo-3QIMQorht3GSrHxBbg3GT1KXrFl=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1mtXo-3QIMQorht3GSrHxBbg3GT1KXrFl=w400"
  },
  {
    "id": "1HO6seCeVutnRuVnVvCA21zzk0vyStjwg",
    "sno": "66",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1HO6seCeVutnRuVnVvCA21zzk0vyStjwg/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1HO6seCeVutnRuVnVvCA21zzk0vyStjwg=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1HO6seCeVutnRuVnVvCA21zzk0vyStjwg=w400"
  },
  {
    "id": "1H47oFNSSVFEnz_fmW7SeW0NAQXUNWQ5q",
    "sno": "67",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1H47oFNSSVFEnz_fmW7SeW0NAQXUNWQ5q/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1H47oFNSSVFEnz_fmW7SeW0NAQXUNWQ5q=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1H47oFNSSVFEnz_fmW7SeW0NAQXUNWQ5q=w400"
  },
  {
    "id": "1KDalT2mX99MonR_Ouqx5g5n_gyT18tVv",
    "sno": "68",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1KDalT2mX99MonR_Ouqx5g5n_gyT18tVv/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1KDalT2mX99MonR_Ouqx5g5n_gyT18tVv=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1KDalT2mX99MonR_Ouqx5g5n_gyT18tVv=w400"
  },
  {
    "id": "15qWf232-ngSKqoBVe-cA7-0LrwNk2ZLZ",
    "sno": "69",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/15qWf232-ngSKqoBVe-cA7-0LrwNk2ZLZ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/15qWf232-ngSKqoBVe-cA7-0LrwNk2ZLZ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/15qWf232-ngSKqoBVe-cA7-0LrwNk2ZLZ=w400"
  },
  {
    "id": "1IYcpMxydcnwRQYh54OXsEe10UoRDoZuO",
    "sno": "70",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1IYcpMxydcnwRQYh54OXsEe10UoRDoZuO/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1IYcpMxydcnwRQYh54OXsEe10UoRDoZuO=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1IYcpMxydcnwRQYh54OXsEe10UoRDoZuO=w400"
  },
  {
    "id": "1xg5tw66JRntT40hojbyG6v-asNmplsiH",
    "sno": "71",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1xg5tw66JRntT40hojbyG6v-asNmplsiH/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1xg5tw66JRntT40hojbyG6v-asNmplsiH=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1xg5tw66JRntT40hojbyG6v-asNmplsiH=w400"
  },
  {
    "id": "1mTSg5wg3ORkbNfzla_Jeo4vJ2XBXkghz",
    "sno": "73",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Washroom",
    "driveLink": "https://drive.google.com/file/d/1mTSg5wg3ORkbNfzla_Jeo4vJ2XBXkghz/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1mTSg5wg3ORkbNfzla_Jeo4vJ2XBXkghz=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1mTSg5wg3ORkbNfzla_Jeo4vJ2XBXkghz=w400"
  },
  {
    "id": "1i5Flnl_lrsWMn6RwZrlk8ge-5uKm0IDW",
    "sno": "74",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Washroom",
    "driveLink": "https://drive.google.com/file/d/1i5Flnl_lrsWMn6RwZrlk8ge-5uKm0IDW/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1i5Flnl_lrsWMn6RwZrlk8ge-5uKm0IDW=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1i5Flnl_lrsWMn6RwZrlk8ge-5uKm0IDW=w400"
  },
  {
    "id": "1U49tG0HNTxcDkkl46Zz31znDHo__ehcr",
    "sno": "75",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Washroom",
    "driveLink": "https://drive.google.com/file/d/1U49tG0HNTxcDkkl46Zz31znDHo__ehcr/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1U49tG0HNTxcDkkl46Zz31znDHo__ehcr=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1U49tG0HNTxcDkkl46Zz31znDHo__ehcr=w400"
  },
  {
    "id": "1E4ZaQRLbGuKb3txmyFDq-1fYojyhdWgG",
    "sno": "76",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Drawing Room",
    "driveLink": "https://drive.google.com/file/d/1E4ZaQRLbGuKb3txmyFDq-1fYojyhdWgG/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1E4ZaQRLbGuKb3txmyFDq-1fYojyhdWgG=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1E4ZaQRLbGuKb3txmyFDq-1fYojyhdWgG=w400"
  },
  {
    "id": "1Ab1FxCNA0OMT2p04aWssiWg66TaFwQKQ",
    "sno": "77",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Washroom",
    "driveLink": "https://drive.google.com/file/d/1Ab1FxCNA0OMT2p04aWssiWg66TaFwQKQ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Ab1FxCNA0OMT2p04aWssiWg66TaFwQKQ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Ab1FxCNA0OMT2p04aWssiWg66TaFwQKQ=w400"
  },
  {
    "id": "1S4GZY2js3Uar3980fYpun74ATGDcC-Ak",
    "sno": "78",
    "theme": "Construction",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Turnkey Construction Project"
    ],
    "software": [],
    "description": "Project: Washroom",
    "driveLink": "https://drive.google.com/file/d/1S4GZY2js3Uar3980fYpun74ATGDcC-Ak/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1S4GZY2js3Uar3980fYpun74ATGDcC-Ak=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1S4GZY2js3Uar3980fYpun74ATGDcC-Ak=w400"
  },
  {
    "id": "1kZ1BvphRLn5sGmBr-L-F6L8pIoY1vw_X",
    "sno": "79",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "AURELIA\n\nMaterial: Premium Walnut Wood\n\nDesign Concept:\nA sculptural luxury console table crafted with a bold architectural presence. The fluted curved base creates a seamless flow of vertical rhythm, while the smooth rounded-edge tabletop balances softness with sophistication. Designed to function as both furniture and statement art, Aurelia brings warmth, texture, and timeless elegance to contemporary interiors.",
    "driveLink": "https://drive.google.com/file/d/1kZ1BvphRLn5sGmBr-L-F6L8pIoY1vw_X/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1kZ1BvphRLn5sGmBr-L-F6L8pIoY1vw_X=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1kZ1BvphRLn5sGmBr-L-F6L8pIoY1vw_X=w400"
  },
  {
    "id": "1RDvGhNR4gG6EALrv2JBfwdMI_yiIMcQ5",
    "sno": "80",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "VETRO\n\nMaterial: Solid Oak Wood\n\nDesign Concept:\nVetro is designed with a timeless minimalist approach that celebrates simplicity, proportion, and craftsmanship. The angled legs create a light architectural stance, while the rounded-edge tabletop softens the geometry for a warm contemporary feel. The open lower shelf adds practicality without compromising the clean aesthetic, making it ideal for modern luxury interiors.",
    "driveLink": "https://drive.google.com/file/d/1RDvGhNR4gG6EALrv2JBfwdMI_yiIMcQ5/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1RDvGhNR4gG6EALrv2JBfwdMI_yiIMcQ5=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1RDvGhNR4gG6EALrv2JBfwdMI_yiIMcQ5=w400"
  },
  {
    "id": "1Hcnoqev_kPrVWYXKsH74YnQ_whNRBOlx",
    "sno": "81",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "SIENNA\n\nMaterial: Ash Wood\n\nDesign Concept:\nSienna blends soft organic curves with refined linear detailing to create a balanced contemporary statement piece. The fluted drawer front introduces texture and rhythm, while the rounded silhouette and cylindrical legs bring warmth and sculptural elegance. Designed for luxurious modern interiors, Sienna offers both functionality and timeless visual appeal.",
    "driveLink": "https://drive.google.com/file/d/1Hcnoqev_kPrVWYXKsH74YnQ_whNRBOlx/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1Hcnoqev_kPrVWYXKsH74YnQ_whNRBOlx=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1Hcnoqev_kPrVWYXKsH74YnQ_whNRBOlx=w400"
  },
  {
    "id": "1YHuv_evc6GhUkcAewW9ho6ojEyBGr5jp",
    "sno": "82",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "LUSSO\n\nMaterial: Solid Walnut Wood\n\nDesign Concept:\nLusso is a bold architectural console table that combines sculptural simplicity with timeless luxury. The thick rounded tabletop and monolithic pedestal legs create a powerful visual presence, while the soft central arch introduces balance and elegance. Crafted to become a statement centerpiece, Lusso reflects refined craftsmanship and modern sophistication.",
    "driveLink": "https://drive.google.com/file/d/1YHuv_evc6GhUkcAewW9ho6ojEyBGr5jp/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1YHuv_evc6GhUkcAewW9ho6ojEyBGr5jp=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1YHuv_evc6GhUkcAewW9ho6ojEyBGr5jp=w400"
  },
  {
    "id": "1HkggrLIvkyavrE3B60bNBnuUiWIxwhRO",
    "sno": "83",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "NOCTURNE\n\nMaterial: Dark Walnut\n\nDesign:\nMonolithic form with seamless curved edges. Deep walnut tones and clean architectural lines create a bold yet understated presence. The continuous silhouette gives the piece a sculptural identity, while its minimal detailing allows the natural grain and craftsmanship to stand out. Designed for modern interiors seeking warmth, sophistication, and timeless character.",
    "driveLink": "https://drive.google.com/file/d/1HkggrLIvkyavrE3B60bNBnuUiWIxwhRO/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1HkggrLIvkyavrE3B60bNBnuUiWIxwhRO=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1HkggrLIvkyavrE3B60bNBnuUiWIxwhRO=w400"
  },
  {
    "id": "1cerCr8vqeKFKA8xAzfnUgoa44vtldrqO",
    "sno": "84",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "HALCYON\n\nMaterial: Maple\n\nDesign:\nA refined balance of softness and structure, HALCYON features a sculptural fluted base paired with a thick oval tabletop. Crafted in light maple wood, the design emphasizes subtle texture, fluid curves, and calm minimalism. Its architectural silhouette brings warmth and elegance to contemporary interiors while maintaining a clean, timeless presence.",
    "driveLink": "https://drive.google.com/file/d/1cerCr8vqeKFKA8xAzfnUgoa44vtldrqO/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1cerCr8vqeKFKA8xAzfnUgoa44vtldrqO=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1cerCr8vqeKFKA8xAzfnUgoa44vtldrqO=w400"
  },
  {
    "id": "13W_UjatGLCS7t2IVU1wpP4h0JygxOuYQ",
    "sno": "85",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "TERRA\n\nMaterial: Mango Wood\n\nDesign:\nTERRA celebrates raw materiality through bold architectural forms and rich natural grain patterns. Featuring faceted angular legs paired with a thick slab-style top, the piece balances rustic warmth with contemporary geometry. The organic textures and earthy character of mango wood make each console unique, creating a grounded yet refined statement for modern interiors.",
    "driveLink": "https://drive.google.com/file/d/13W_UjatGLCS7t2IVU1wpP4h0JygxOuYQ/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/13W_UjatGLCS7t2IVU1wpP4h0JygxOuYQ=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/13W_UjatGLCS7t2IVU1wpP4h0JygxOuYQ=w400"
  },
  {
    "id": "1vRZwnAUh44cMzKm8zXtA2BD9qhfjQ7PF",
    "sno": "86",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "ELYSIAN\n\nMaterial: Cherry Wood\n\nDesign:\nELYSIAN combines sculptural elegance with architectural simplicity through its graceful arched base and softly rounded tabletop. Crafted in rich cherry wood, the design highlights warm tones, flowing curves, and refined proportions. The bold central arch creates a striking visual identity while maintaining an understated sophistication suited for timeless contemporary interiors.",
    "driveLink": "https://drive.google.com/file/d/1vRZwnAUh44cMzKm8zXtA2BD9qhfjQ7PF/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1vRZwnAUh44cMzKm8zXtA2BD9qhfjQ7PF=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1vRZwnAUh44cMzKm8zXtA2BD9qhfjQ7PF=w400"
  },
  {
    "id": "1jxJvG-B2vpGsMvirMGn5IBEqeXts3Ate",
    "sno": "87",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "ORION\n\nMaterial: Acacia Wood\n\nDesign: Chevron-patterned front with hidden drawers. Slim tapered legs add lightness and mid-century influence. The geometric wood grain creates a refined visual rhythm, while the elongated silhouette offers both elegance and functionality. A timeless statement piece inspired by classic mid-century modern craftsmanship.",
    "driveLink": "https://drive.google.com/file/d/1jxJvG-B2vpGsMvirMGn5IBEqeXts3Ate/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1jxJvG-B2vpGsMvirMGn5IBEqeXts3Ate=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1jxJvG-B2vpGsMvirMGn5IBEqeXts3Ate=w400"
  },
  {
    "id": "1TwNpO_tkS1QCiGNChBq2lre-wC83pLCq",
    "sno": "88",
    "theme": "Furniture",
    "country": null,
    "state": null,
    "city": null,
    "clientType": "Individual Home Owner",
    "clientName": null,
    "services": [
      "Furniture Design",
      "Interior Design"
    ],
    "software": [],
    "description": "VERDE\n\nMaterial: Reclaimed Wood\n\nDesign: Rustic yet refined with a live-edge top and thick slab legs. Authentic beauty with natural character. Earthy textures and rich grain make it a grounded, versatile piece that brings warmth and organic elegance to any space. Sustainably sourced and crafted to celebrate the uniqueness of reclaimed wood.",
    "driveLink": "https://drive.google.com/file/d/1TwNpO_tkS1QCiGNChBq2lre-wC83pLCq/view?usp=drive_link",
    "type": "image",
    "src": "https://lh3.googleusercontent.com/d/1TwNpO_tkS1QCiGNChBq2lre-wC83pLCq=w1600",
    "thumb": "https://lh3.googleusercontent.com/d/1TwNpO_tkS1QCiGNChBq2lre-wC83pLCq=w400"
  }
];

export const GALLERY_VIDEOS = [
  {
    "id": "1ukYRKITrTW-DIjh2qvt2odRBUnK25aG0",
    "sno": "44",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential House",
    "driveLink": "https://drive.google.com/file/d/1ukYRKITrTW-DIjh2qvt2odRBUnK25aG0/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1ukYRKITrTW-DIjh2qvt2odRBUnK25aG0/preview",
    "poster": "https://lh3.googleusercontent.com/d/1ukYRKITrTW-DIjh2qvt2odRBUnK25aG0=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1ukYRKITrTW-DIjh2qvt2odRBUnK25aG0=w400"
  },
  {
    "id": "1YqRVfdMpziCtj6KnJ6tdWiDcsH5F7cQY",
    "sno": "45",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Mohali",
    "clientType": "Architectural Firm",
    "clientName": "Design Anthem Forum",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Modern Residential House",
    "driveLink": "https://drive.google.com/file/d/1YqRVfdMpziCtj6KnJ6tdWiDcsH5F7cQY/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1YqRVfdMpziCtj6KnJ6tdWiDcsH5F7cQY/preview",
    "poster": "https://lh3.googleusercontent.com/d/1YqRVfdMpziCtj6KnJ6tdWiDcsH5F7cQY=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1YqRVfdMpziCtj6KnJ6tdWiDcsH5F7cQY=w400"
  },
  {
    "id": "1vHMKMkD3vHYGig5eKxy691GDwXyo8xyy",
    "sno": "46",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Radha Krishna Temple",
    "driveLink": "https://drive.google.com/file/d/1vHMKMkD3vHYGig5eKxy691GDwXyo8xyy/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1vHMKMkD3vHYGig5eKxy691GDwXyo8xyy/preview",
    "poster": "https://lh3.googleusercontent.com/d/1vHMKMkD3vHYGig5eKxy691GDwXyo8xyy=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1vHMKMkD3vHYGig5eKxy691GDwXyo8xyy=w400"
  },
  {
    "id": "1TnI5RVS7lZHwmSHRBl26m_XBsFUXw48K",
    "sno": "47",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1TnI5RVS7lZHwmSHRBl26m_XBsFUXw48K/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1TnI5RVS7lZHwmSHRBl26m_XBsFUXw48K/preview",
    "poster": "https://lh3.googleusercontent.com/d/1TnI5RVS7lZHwmSHRBl26m_XBsFUXw48K=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1TnI5RVS7lZHwmSHRBl26m_XBsFUXw48K=w400"
  },
  {
    "id": "1-fGdMuNzFYuHjMzhnNF847nXa6DlAPY1",
    "sno": "48",
    "theme": "Exterior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1-fGdMuNzFYuHjMzhnNF847nXa6DlAPY1/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1-fGdMuNzFYuHjMzhnNF847nXa6DlAPY1/preview",
    "poster": "https://lh3.googleusercontent.com/d/1-fGdMuNzFYuHjMzhnNF847nXa6DlAPY1=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1-fGdMuNzFYuHjMzhnNF847nXa6DlAPY1=w400"
  },
  {
    "id": "1a407hbijr-HkL6eGMDgVJPmgq8olpomF",
    "sno": "49",
    "theme": "Interior",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "clientType": "Architectural Firm",
    "clientName": "Mr.Raman- Ideal Home Designers",
    "services": [
      "3D Walkthrough Animation",
      "Interior 3D rendering"
    ],
    "software": [],
    "description": "Project: Drawing Room",
    "driveLink": "https://drive.google.com/file/d/1a407hbijr-HkL6eGMDgVJPmgq8olpomF/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1a407hbijr-HkL6eGMDgVJPmgq8olpomF/preview",
    "poster": "https://lh3.googleusercontent.com/d/1a407hbijr-HkL6eGMDgVJPmgq8olpomF=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1a407hbijr-HkL6eGMDgVJPmgq8olpomF=w400"
  },
  {
    "id": "1AHvviGK34os-vhAZ7N8EpOVZP7YDfL4V",
    "sno": "50",
    "theme": "Exterior",
    "country": "India",
    "state": "Delhi",
    "city": null,
    "clientType": "Interior Designers",
    "clientName": "Mr.Shiv - Harmony Interiors",
    "services": [
      "3D Walkthrough Animation",
      "Exterior 3D Rendering"
    ],
    "software": [],
    "description": "Project: Hut Residencial House",
    "driveLink": "https://drive.google.com/file/d/1AHvviGK34os-vhAZ7N8EpOVZP7YDfL4V/view?usp=drive_link",
    "type": "video",
    "src": "https://drive.google.com/file/d/1AHvviGK34os-vhAZ7N8EpOVZP7YDfL4V/preview",
    "poster": "https://lh3.googleusercontent.com/d/1AHvviGK34os-vhAZ7N8EpOVZP7YDfL4V=w800",
    "thumb": "https://lh3.googleusercontent.com/d/1AHvviGK34os-vhAZ7N8EpOVZP7YDfL4V=w400"
  }
];
