// Auto-generated by scripts/build-gallery-manifest.js — do not edit manually.
export const GALLERY_IMAGES = [
  {
    "src": "/gallery/optimized/1-jpg.webp",
    "thumb": "/gallery/optimized/1-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/1-png.webp",
    "thumb": "/gallery/optimized/1-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/2-2-jpg.webp",
    "thumb": "/gallery/optimized/2-2-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/2-37-jpg.webp",
    "thumb": "/gallery/optimized/2-37-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/2-42-jpg.webp",
    "thumb": "/gallery/optimized/2-42-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/2-png.webp",
    "thumb": "/gallery/optimized/2-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/3_7---photo-10-1-jpg.webp",
    "thumb": "/gallery/optimized/3_7---photo-10-1-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/3_7---photo-10-jpg.webp",
    "thumb": "/gallery/optimized/3_7---photo-10-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/3bcfa0de-89e5-4adf-abfd-3f7330370a08-jpg.webp",
    "thumb": "/gallery/optimized/3bcfa0de-89e5-4adf-abfd-3f7330370a08-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/03eadce5-7fa6-4e27-9c4d-e53c4a278fa0-jpg.webp",
    "thumb": "/gallery/optimized/03eadce5-7fa6-4e27-9c4d-e53c4a278fa0-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/4-71-jpg.webp",
    "thumb": "/gallery/optimized/4-71-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/5-jpg.webp",
    "thumb": "/gallery/optimized/5-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/6-jpg.webp",
    "thumb": "/gallery/optimized/6-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/7-jpg.webp",
    "thumb": "/gallery/optimized/7-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/8-jpg.webp",
    "thumb": "/gallery/optimized/8-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/11-1-jpg.webp",
    "thumb": "/gallery/optimized/11-1-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/11-jpg.webp",
    "thumb": "/gallery/optimized/11-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/12-jpg.webp",
    "thumb": "/gallery/optimized/12-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/13-7-jpg.webp",
    "thumb": "/gallery/optimized/13-7-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/13-15-jpg.webp",
    "thumb": "/gallery/optimized/13-15-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/14-1-jpg.webp",
    "thumb": "/gallery/optimized/14-1-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/18-5-jpg.webp",
    "thumb": "/gallery/optimized/18-5-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/392f8d0d-0270-4094-88c1-0c577e48007d-jpg.webp",
    "thumb": "/gallery/optimized/392f8d0d-0270-4094-88c1-0c577e48007d-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/588a4409-552c-4b6e-aa7b-f1de7f7c8177-jpg.webp",
    "thumb": "/gallery/optimized/588a4409-552c-4b6e-aa7b-f1de7f7c8177-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/638f0980-2c32-4058-ada7-58345a93941b-jpg.webp",
    "thumb": "/gallery/optimized/638f0980-2c32-4058-ada7-58345a93941b-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/a_5---photo-19-jpg.webp",
    "thumb": "/gallery/optimized/a_5---photo-19-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/b-48-jpg.webp",
    "thumb": "/gallery/optimized/b-48-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/blue-aesthetic-mood-board-brand-inspiration-poster-png.webp",
    "thumb": "/gallery/optimized/blue-aesthetic-mood-board-brand-inspiration-poster-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/brown-and-beige-modern-interior-design-instagram-post-png.webp",
    "thumb": "/gallery/optimized/brown-and-beige-modern-interior-design-instagram-post-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/c_13---photo-jpg.webp",
    "thumb": "/gallery/optimized/c_13---photo-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/c6dc7f16-5a8d-4b29-9142-c4d7bbacde7d-jpg.webp",
    "thumb": "/gallery/optimized/c6dc7f16-5a8d-4b29-9142-c4d7bbacde7d-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/chatgpt-image-feb-3-2026-05_35_56-pm-png.webp",
    "thumb": "/gallery/optimized/chatgpt-image-feb-3-2026-05_35_56-pm-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/day-jpg.webp",
    "thumb": "/gallery/optimized/day-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/doc-20250105-wa0000-jpg.webp",
    "thumb": "/gallery/optimized/doc-20250105-wa0000-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/f5a16ac8-0b8a-468f-857f-443e41ddb348-jpg.webp",
    "thumb": "/gallery/optimized/f5a16ac8-0b8a-468f-857f-443e41ddb348-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/fc61fa91-4e30-416a-a2ad-6c2142d1188f-jpg.webp",
    "thumb": "/gallery/optimized/fc61fa91-4e30-416a-a2ad-6c2142d1188f-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/fuhf-png.webp",
    "thumb": "/gallery/optimized/fuhf-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/gujdf-png.webp",
    "thumb": "/gallery/optimized/gujdf-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_5329-png.webp",
    "thumb": "/gallery/optimized/img_5329-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_5333-png.webp",
    "thumb": "/gallery/optimized/img_5333-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_5335-png.webp",
    "thumb": "/gallery/optimized/img_5335-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_5336-copy-jpg.webp",
    "thumb": "/gallery/optimized/img_5336-copy-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_5342-copy-jpg.webp",
    "thumb": "/gallery/optimized/img_5342-copy-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img_20260214_182502-png.webp",
    "thumb": "/gallery/optimized/img_20260214_182502-png.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img-20240926-wa0039-jpg.webp",
    "thumb": "/gallery/optimized/img-20240926-wa0039-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/img-20250424-wa0004-jpg.webp",
    "thumb": "/gallery/optimized/img-20250424-wa0004-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/lobby-3-1-jpg.webp",
    "thumb": "/gallery/optimized/lobby-3-1-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/night-jpg.webp",
    "thumb": "/gallery/optimized/night-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/pardeep-copy-jpg.webp",
    "thumb": "/gallery/optimized/pardeep-copy-jpg.thumb.webp"
  },
  {
    "src": "/gallery/optimized/screenshot_2025-05-12-17-11-27-67_92460851df6f172a4592fca41cc2d2e6-jpg.webp",
    "thumb": "/gallery/optimized/screenshot_2025-05-12-17-11-27-67_92460851df6f172a4592fca41cc2d2e6-jpg.thumb.webp"
  }
];

export const GALLERY_VIDEOS = [
  {
    "src": "/gallery/videos/1.mov"
  },
  {
    "src": "/gallery/videos/1.mp4"
  },
  {
    "src": "/gallery/videos/2.mp4"
  },
  {
    "src": "/gallery/videos/short.mp4"
  }
];
