// Location landing pages — drives /locations/<slug>.

export const LOCATIONS = [
    {
        slug: 'delhi-ncr',
        city: 'Delhi-NCR',
        country: 'India',
        market: 'india',
        title: '3D Rendering in Delhi-NCR | Architectural Visualization Studio',
        description: 'Photorealistic 3D rendering studio serving Delhi, Noida and Gurgaon. Exterior & interior renders, walkthroughs, 360° tours. India-based pricing.',
        h1: '3D Architectural Rendering in Delhi-NCR',
        hook: "Delhi-NCR is India's largest real-estate market. Noida and Gurgaon are in a commercial-tower and high-rise residential boom, the metro keeps reshaping demand corridors, and developers are competing for buyer attention with ever-better marketing assets. Photoreal 3D renders, walkthroughs and 360° tours are now table-stakes for any pre-launch.",
        intro: "Ideal Visualizations works with architecture firms in Connaught Place and Saket, interior designers across South Delhi and Gurgaon, and developers building across Noida, Greater Noida, Gurgaon and Faridabad. We deliver remote from our Amritsar studio (a 6-hour drive) with same-day WhatsApp turnaround on briefs and revisions.",
        portfolioNote: '[Danish to provide 2–3 Delhi-NCR projects with images, scope and turnaround]',
        availability: 'We serve Delhi-NCR clients remotely with same-day WhatsApp turnaround. Site visits to Delhi, Gurgaon and Noida are arranged on request.',
        pricingNote: 'Competitive India-based pricing for Delhi-NCR clients — typically 30–50% lower than NCR-based studios.',
        showMap: false,
    },
    {
        slug: 'dubai',
        city: 'Dubai',
        country: 'UAE',
        market: 'uae',
        title: '3D Rendering Studio in Dubai | Architectural Visualization for UAE',
        description: 'Photorealistic 3D rendering for Dubai and UAE real-estate developers, architects and interior designers. Off-plan launches, luxury residential, hospitality.',
        h1: '3D Architectural Rendering for Dubai',
        hook: "Dubai's real-estate market runs on off-plan sales — and off-plan sales run on photoreal renders, cinematic walkthroughs and 360° tours. From Downtown towers to Palm villas to Dubai Hills mid-rise, the visual standard is uncompromising and the launch timelines are short.",
        intro: "We serve UAE clients remotely from our Amritsar studio. Time-zone overlap is excellent (UAE is only 1.5 hours behind India), English is the working language, and our pricing is typically 60–80% lower than Dubai-based studios for an equivalent quality of output. We have delivered exterior renders, interior unit-type sets, master-plan flythroughs and 360° tours for residential, hospitality and commercial launches.",
        portfolioNote: '[Danish to provide 2–3 Dubai/UAE projects]',
        availability: "We serve Dubai clients remotely. Communication via WhatsApp, email and Zoom. Time-zone overlap means same-day responses on briefs and revisions.",
        pricingNote: 'India-based pricing for UAE clients — typically 60–80% lower than Dubai studios for equivalent quality.',
        showMap: false,
    },
    {
        slug: 'chandigarh',
        city: 'Chandigarh',
        country: 'India',
        market: 'india',
        title: '3D Rendering in Chandigarh, Mohali & Panchkula | Tricity Studio',
        description: 'Photorealistic 3D rendering for Chandigarh, Mohali and Panchkula architects, designers and developers. Local studio with same-day site visits.',
        h1: '3D Architectural Rendering in Chandigarh',
        hook: "Chandigarh's tricity (Chandigarh + Mohali + Panchkula) is one of India's most design-aware markets — Le Corbusier's modernist legacy still shapes how buildings are judged here. Modern bungalows in Sectors 8 and 9, mid-rise residential in Mohali Sector 70, and commercial in IT Park all need rendering quality that matches the city's architectural standards.",
        intro: "Chandigarh is our backyard — a 4-hour drive from our Amritsar headquarters. We do regular site visits to Chandigarh, Mohali and Panchkula and have delivered renders, walkthroughs and 360° tours for residential bungalows, commercial buildings and hospitality projects across the tricity.",
        portfolioNote: '[Danish to provide 2–3 tricity projects]',
        availability: 'Site visits to Chandigarh, Mohali and Panchkula on demand. Same-day WhatsApp turnaround for remote work.',
        pricingNote: 'Local pricing for tricity clients — no markup for outstation work.',
        showMap: false,
    },
    {
        slug: 'mumbai',
        city: 'Mumbai',
        country: 'India',
        market: 'india',
        title: '3D Rendering in Mumbai | High-Rise & Premium Interior Visualization',
        description: 'Photorealistic 3D rendering for Mumbai architects, designers and developers. High-rise towers, premium interiors, redevelopment marketing renders.',
        h1: '3D Architectural Rendering in Mumbai',
        hook: "Mumbai is India's high-rise capital. Floor plates are tight, premiums are high, and every square foot must justify its price. That makes photoreal rendering non-negotiable — buyers paying ₹40,000+/sq ft expect to see exactly what they are paying for.",
        intro: "We work with Mumbai-based architects in Bandra, Lower Parel and Andheri, interior designers serving South Mumbai residences, and developers running redevelopment projects across the western and eastern suburbs. Our renders capture the way Mumbai light falls — soft monsoon greys, harsh April sun, glittering sea-facing twilights.",
        portfolioNote: '[Danish to provide 2–3 Mumbai projects]',
        availability: 'We serve Mumbai clients remotely from our Amritsar studio. Same-day WhatsApp turnaround. Site visits arranged on request.',
        pricingNote: 'India-based pricing — typically 40–60% lower than Mumbai-based rendering studios.',
        showMap: false,
    },
    {
        slug: 'amritsar',
        city: 'Amritsar',
        country: 'India',
        market: 'india',
        title: '3D Rendering in Amritsar | Architectural Visualization & Turnkey Construction',
        description: 'Amritsar-based 3D rendering, architecture, interior design and turnkey construction studio. Walk-in consultations available at our Amritsar HQ.',
        h1: '3D Architectural Rendering in Amritsar',
        hook: "Amritsar is our home. From heritage walled-city renovations to modern bungalows in Ranjit Avenue and Green Avenue to commercial fitouts on Mall Road and Lawrence Road — we know how this city builds.",
        intro: "Amritsar is the only city where we offer the full range of services in person — 3D rendering, architecture planning, elevation design, interior design and turnkey construction. Walk-in consultations are available at our headquarters; site visits anywhere in Amritsar can usually be done within 24 hours.",
        portfolioNote: '[Danish to provide 2–3 Amritsar projects]',
        availability: 'Walk-in consultations at our Amritsar HQ. Same-day site visits across the city.',
        pricingNote: 'Local pricing for Amritsar clients. Turnkey construction quoted after a free site visit.',
        showMap: true,
    },
    {
        slug: 'toronto',
        city: 'Toronto',
        country: 'Canada',
        market: 'canada',
        title: '3D Rendering for Toronto Architects & Developers | India-Based Studio',
        description: 'Photorealistic 3D rendering for Toronto architects, interior designers and condo developers. Cost-effective India-based studio with North American time-zone coverage.',
        h1: '3D Architectural Rendering for Toronto',
        hook: "Toronto's condo market is one of the most rendering-dependent in North America. Pre-construction sales depend entirely on photoreal exterior renders, lobby visualisations and unit-type interiors. Architects and developers across the GTA increasingly outsource to international studios for cost and capacity reasons.",
        intro: "We serve Toronto clients remotely from our Amritsar studio. Indian studios offer 3–5x cost advantage over Toronto-based rendering houses without quality compromise — we use the same V-Ray, Corona and Unreal Engine pipelines, the same trained artists, the same delivery standards. Time-zone management is straightforward: we work the early morning EST overlap and use async workflows for the rest.",
        portfolioNote: '[Danish to provide 2–3 Canadian/US projects]',
        availability: "Remote-only. Communication via email, WhatsApp and Zoom (early morning EST overlap with our team's late afternoon). Async file sharing via WeTransfer or your preferred platform.",
        pricingNote: 'India-based pricing for Toronto clients — typically 60–80% lower than GTA studios for equivalent output.',
        showMap: false,
    },
    {
        slug: 'new-york',
        city: 'New York',
        country: 'USA',
        market: 'us',
        title: '3D Rendering for New York Architects & Developers | India-Based Studio',
        description: 'Photorealistic 3D rendering for New York architects, designers and luxury residential developers. India-based studio, US-quality output, 60–80% cost savings.',
        h1: '3D Architectural Rendering for New York',
        hook: "New York architecture firms run on tight deadlines and tighter margins. Outsourcing rendering to a high-quality India-based studio frees designers to focus on design — and frees firms to take on more projects without scaling headcount.",
        intro: "We work with New York firms on luxury residential, commercial office and hospitality projects. Our deliverable standards match Manhattan's expectations — we use V-Ray, Corona and Unreal Engine, deliver in your firm's preferred file format, and follow your house style guide for camera, lighting and post-production.",
        portfolioNote: '[Danish to provide 2–3 US projects]',
        availability: 'Remote-only. Async-first workflow with morning EST overlap for live calls. Slack, email and WhatsApp supported.',
        pricingNote: 'India-based pricing for NYC clients — typically 70–80% lower than Manhattan rendering studios.',
        showMap: false,
    },
];

export const LOCATION_BY_SLUG = Object.fromEntries(LOCATIONS.map((l) => [l.slug, l]));
