// Portfolio case studies. All projects use placeholder data — Danish to fill in real details.

export const PORTFOLIO = [
    {
        slug: 'luxury-villa-chandigarh',
        name: 'Luxury Villa, Chandigarh',
        city: 'Chandigarh',
        type: 'Residential',
        clientType: 'Architect',
        services: ['Exterior 3D Rendering', 'Interior 3D Rendering'],
        software: '3ds Max + V-Ray',
        scope: '6 exterior views (daylight + twilight) and 8 interior views across living, dining, master bedroom and kitchen.',
        challenge: 'Architect needed renders within 10 days for a high-net-worth client approval meeting. Brief called for warm twilight exteriors that emphasised the natural stone façade.',
        solution: 'We rebuilt the SketchUp model to render-quality, sourced PBR textures matching the specified Kota and Dholpur stone, and lit the exterior with a custom HDRI for the twilight hero shot.',
        turnaround: '9 business days',
        results: '[Danish to add: client feedback or outcome — e.g. "Project approved on first presentation."]',
        gallery: ['/3D-Images/1.jpg', '/3D-Images/2 (2).jpg'],
        placeholder: true,
    },
    {
        slug: 'commercial-tower-gurgaon',
        name: 'Commercial Tower, Gurgaon',
        city: 'Gurgaon',
        type: 'Commercial',
        clientType: 'Developer',
        services: ['Exterior 3D Rendering', '3D Walkthrough'],
        software: '3ds Max + Corona, Lumion',
        scope: 'Hero exterior render + 90-second cinematic walkthrough covering entry, lobby and typical office floor.',
        challenge: 'Developer was launching pre-leasing and needed a cinematic asset that worked equally well on YouTube, Instagram and the sales-office screen.',
        solution: 'We delivered a 4K 60fps walkthrough plus a 9:16 vertical cut for Instagram Reels and the same scene as a static hero render.',
        turnaround: '18 business days',
        results: '[Danish to add: leasing outcome]',
        gallery: ['/3D-Images/2.png'],
        placeholder: true,
    },
    {
        slug: 'boutique-hotel-dubai',
        name: 'Boutique Hotel, Dubai',
        city: 'Dubai',
        type: 'Hospitality',
        clientType: 'Developer',
        services: ['Interior 3D Rendering', '360° Virtual Tour'],
        software: '3ds Max + V-Ray',
        scope: '12 interior renders (lobby, restaurant, suite types, spa) plus interactive 360° tour of the lobby and one suite.',
        challenge: 'Off-plan launch in Dubai required photoreal interiors that matched the brand book of a luxury hospitality group.',
        solution: 'We worked from the brand book and material library to deliver renders that the developer used in their Cityscape Dubai launch and embedded the 360° tour in their pre-sales website.',
        turnaround: '24 business days',
        results: '[Danish to add: pre-sales bookings]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'modern-bungalow-mohali',
        name: 'Modern Bungalow, Mohali',
        city: 'Mohali',
        type: 'Residential',
        clientType: 'Turnkey Client',
        services: ['Architecture Planning', 'Elevation Design', 'Exterior 3D Rendering', 'Turnkey Construction'],
        software: 'AutoCAD, SketchUp, 3ds Max + V-Ray',
        scope: 'Full architectural planning, elevation design, exterior renders, interior design and turnkey construction of a 4,500 sq ft modern bungalow.',
        challenge: 'Client wanted an end-to-end partner — design, approvals, construction and handover — without managing multiple vendors.',
        solution: 'We delivered the full turnkey package from a clean-sheet brief to handover in 11 months, with photoreal renders at every milestone for client approval.',
        turnaround: '11 months end-to-end',
        results: '[Danish to add: client testimonial]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'restaurant-fitout-amritsar',
        name: 'Restaurant Fitout, Amritsar',
        city: 'Amritsar',
        type: 'Hospitality',
        clientType: 'Restaurateur',
        services: ['Interior Design', 'Interior 3D Rendering', 'Turnkey Construction'],
        software: 'SketchUp, 3ds Max + Corona',
        scope: '80-cover restaurant interior design with 6 photoreal renders and turnkey construction.',
        challenge: 'Tight 4-month timeline from brief to opening night for an 80-cover restaurant in central Amritsar.',
        solution: 'Renders approved in week 2, construction started week 3, soft launch in week 16.',
        turnaround: '4 months',
        results: '[Danish to add: opening details]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'residential-tower-mumbai',
        name: 'Residential Tower, Mumbai',
        city: 'Mumbai',
        type: 'Residential',
        clientType: 'Developer',
        services: ['Exterior 3D Rendering', 'Interior 3D Rendering', '3D Walkthrough', '360° Virtual Tour'],
        software: '3ds Max + V-Ray, Lumion',
        scope: '28-storey tower launch bundle: hero exterior, master plan, 4 typical-unit interior sets, 90s walkthrough, 360° tour of one show flat.',
        challenge: 'Sea-facing tower with premium ₹35,000+/sq ft pricing demanded uncompromising visual quality for Mumbai buyers.',
        solution: 'We treated the hero shot like a film frame — custom HDRI, multi-pass post-production, sea-spray and sky atmospherics added in Photoshop.',
        turnaround: '6 weeks',
        results: '[Danish to add: pre-launch bookings]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'co-working-office-bangalore',
        name: 'Co-Working Office, Bangalore',
        city: 'Bangalore',
        type: 'Commercial',
        clientType: 'Interior Designer',
        services: ['Interior 3D Rendering'],
        software: '3ds Max + Corona',
        scope: '8 interior renders covering open workstations, phone booths, meeting rooms, café and reception.',
        challenge: 'Designer needed renders to compete in a multi-firm pitch for a 25,000 sq ft co-working brand expansion.',
        solution: 'Bright, brand-aligned renders delivered in 8 business days. Designer won the pitch.',
        turnaround: '8 business days',
        results: '[Danish to add: pitch outcome]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'villa-cluster-noida',
        name: 'Villa Cluster, Noida',
        city: 'Noida',
        type: 'Residential',
        clientType: 'Developer',
        services: ['Exterior 3D Rendering', '3D Walkthrough', 'Aerial Render'],
        software: '3ds Max + V-Ray',
        scope: '12-villa luxury cluster — aerial master-plan, 4 villa-type exteriors, 60s aerial fly-through.',
        challenge: 'Pre-launch needed both an aerial overview and ground-level realism for the four typical villa types.',
        solution: 'Combined V-Ray for stills with a Lumion fly-through, edited together in After Effects with brand music.',
        turnaround: '4 weeks',
        results: '[Danish to add]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'penthouse-dubai',
        name: 'Penthouse Interior, Dubai',
        city: 'Dubai',
        type: 'Residential',
        clientType: 'Interior Designer',
        services: ['Interior 3D Rendering', '360° Virtual Tour'],
        software: '3ds Max + Corona',
        scope: 'Full-floor penthouse interior: 10 photoreal interior renders + 360° tour.',
        challenge: 'High-end Dubai client wanted to walk the apartment in VR before construction completion.',
        solution: '360° tour deployed to the designer\'s iPad with hotspot navigation between rooms.',
        turnaround: '14 business days',
        results: '[Danish to add]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'condo-development-toronto',
        name: 'Condo Development, Toronto',
        city: 'Toronto',
        type: 'Residential',
        clientType: 'Developer',
        services: ['Exterior 3D Rendering', 'Interior 3D Rendering', '3D Walkthrough'],
        software: '3ds Max + V-Ray, Unreal Engine',
        scope: 'Pre-construction launch bundle for a 22-storey GTA condo: exterior hero, lobby + amenities + 3 unit-type interiors + 90s walkthrough.',
        challenge: 'Canadian developer needed launch assets matching local market expectations at non-Toronto pricing.',
        solution: 'Async workflow with morning-EST overlap. Delivered in 5 weeks at ~30% of a Toronto studio quote.',
        turnaround: '5 weeks',
        results: '[Danish to add]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'commercial-fitout-new-york',
        name: 'Commercial Fitout, New York',
        city: 'New York',
        type: 'Commercial',
        clientType: 'Architect',
        services: ['Interior 3D Rendering'],
        software: '3ds Max + V-Ray',
        scope: '6 interior renders for a Manhattan office fitout pitch.',
        challenge: 'Manhattan firm needed pitch-grade interiors in 7 business days against a competitor.',
        solution: 'Delivered 6 hero renders on day 7. Firm won the project.',
        turnaround: '7 business days',
        results: '[Danish to add]',
        gallery: [],
        placeholder: true,
    },
    {
        slug: 'heritage-renovation-amritsar',
        name: 'Heritage Renovation, Amritsar',
        city: 'Amritsar',
        type: 'Heritage / Renovation',
        clientType: 'Private Owner',
        services: ['Architecture Planning', 'Interior Design', 'Interior 3D Rendering', 'Turnkey Construction'],
        software: 'AutoCAD, SketchUp, 3ds Max + Corona',
        scope: 'Walled-city heritage haveli renovation — preservation-led planning, interior design and turnkey execution.',
        challenge: 'Preserve original architectural elements (jharokhas, courtyards, lime plaster) while inserting modern services.',
        solution: 'Phased planning with renders showing each phase of intervention. Construction respected existing material vocabulary.',
        turnaround: '14 months',
        results: '[Danish to add]',
        gallery: [],
        placeholder: true,
    },
];

export const PORTFOLIO_BY_SLUG = Object.fromEntries(PORTFOLIO.map((p) => [p.slug, p]));
