// Service definitions — drives /services hub, individual service pages, and sitemap.
// Each service maps to /services/<slug>.

export const SERVICES = [
    {
        slug: 'exterior-3d-rendering',
        name: 'Exterior 3D Rendering',
        category: '3D Visualization',
        title: 'Exterior 3D Rendering Services | Photorealistic Architectural Visualization',
        description: 'Photorealistic exterior 3D renders for residential, commercial & hospitality projects. Daylight, twilight & aerial views. 5–10 day turnaround.',
        h1: 'Exterior 3D Rendering',
        intro: "Exterior 3D rendering turns architectural plans, elevations and SketchUp files into photorealistic still images that show a building exactly as it will look once built — its façade, materials, surroundings, lighting and landscape, all believable enough to use in client presentations, planning submissions and pre-sales marketing.",
        secondary: "We deliver exterior renders for architects, real-estate developers and turnkey contractors across India, the UAE, the US and Canada. Send us your CAD, SketchUp or Revit file along with material references and a few image samples you like, and we handle the rest — modeling, materials, lighting, post-production and delivery.",
        types: [
            { name: 'Daylight views', desc: 'Bright, natural sunlight renders that emphasise materials, texture and landscape design.' },
            { name: 'Twilight & dusk views', desc: 'Warm interior glow against a cool sky — the highest-converting hero render for real estate marketing.' },
            { name: 'Aerial / bird’s-eye views', desc: 'Drone-style perspectives for master plans, townships and large commercial sites.' },
            { name: 'Street-level perspectives', desc: 'Eye-level views that show the building in human context — perfect for planning approvals.' },
            { name: 'Landscaping visualisation', desc: 'Hardscape, plantings, water features and outdoor lighting rendered to scale.' },
        ],
        process: [
            'Receive your CAD, SketchUp, Revit or PDF plans plus material references.',
            '3D modeling: we rebuild the geometry to render-quality standards.',
            'Material & texture assignment with PBR-accurate maps.',
            'Lighting setup: sun position, time of day, sky model, artificial lighting.',
            'Rendering with V-Ray or Corona for maximum photorealism.',
            'Post-production in Photoshop: colour grading, atmospheric depth, entourage.',
            'Review, two free revision rounds, then high-resolution delivery.',
        ],
        software: '3ds Max + V-Ray / Corona for the photorealistic finish, Lumion for fast preview turnarounds, Unreal Engine for real-time and VR experiences.',
        turnaround: '5–10 business days per view (standard), 2–3 days available on rush.',
        pricing: 'Starts from ₹[AMOUNT] per view for India clients / $[AMOUNT] for international clients. Volume pricing kicks in at 5+ views.',
        gallery: [
            { src: '/3D-Images/1.jpg', alt: 'Twilight exterior render of a modern residential villa' },
            { src: '/3D-Images/1.png', alt: 'Contemporary façade elevation rendering' },
            { src: '/3D-Images/2 (2).jpg', alt: 'Day-time exterior architectural visualization' },
            { src: '/3D-Images/2.png', alt: 'Photorealistic exterior with cinematic lighting' },
        ],
        related: ['interior-3d-rendering', '3d-walkthrough-animation', '360-virtual-tour'],
        relatedBlog: ['exterior-vs-interior-rendering', '3d-rendering-cost'],
    },
    {
        slug: 'interior-3d-rendering',
        name: 'Interior 3D Rendering',
        category: '3D Visualization',
        title: 'Interior 3D Rendering Services | Realistic Interior Visualization',
        description: 'Photorealistic interior 3D renders with cinematic lighting and material accuracy. Residential, commercial, hospitality. 5–10 day delivery.',
        h1: 'Interior 3D Rendering',
        intro: "Interior 3D rendering converts a floor plan and a mood board into a photorealistic still that shows exactly how a finished space will feel — the warmth of the lighting, the grain of the timber, the colour of the walls, the way an evening sun lands on a sofa. It is the single fastest way to get a client to say yes.",
        secondary: "We render living rooms, bedrooms, kitchens, bathrooms, offices, lobbies, restaurants, retail fitouts and hospitality suites. Send us your floor plan, elevations and any reference photos, and we will return a photoreal frame that closes the conversation.",
        types: [
            { name: 'Residential interiors', desc: 'Living rooms, bedrooms, kitchens and bathrooms with warm, lived-in lighting.' },
            { name: 'Commercial & office', desc: 'Workspaces, meeting rooms and reception areas with bright, neutral lighting.' },
            { name: 'Hospitality', desc: 'Restaurants, hotels and lobbies with dramatic, cinematic lighting.' },
            { name: 'Retail & showroom', desc: 'Product-forward lighting that puts merchandise centre-stage.' },
            { name: 'Material & lighting studies', desc: 'Multiple variants of the same view to compare finishes and lighting moods.' },
        ],
        process: [
            'Receive floor plans, elevations and your mood board / reference images.',
            '3D modeling of walls, ceilings, floors and built-in joinery.',
            'Furniture and props placed from our curated library or your specifications.',
            'Materials and finishes mapped from your samples or supplier catalogues.',
            'Lighting setup — natural, artificial or mixed, with mood variants on request.',
            'Photorealistic rendering with V-Ray or Corona.',
            'Post-production, two revision rounds, final delivery.',
        ],
        software: '3ds Max + Corona Renderer for interiors (industry-standard for material realism), V-Ray for hero shots, Lumion for fast previews.',
        turnaround: '5–10 business days per view (standard), 2–3 days on rush.',
        pricing: 'Starts from ₹[AMOUNT] per view / $[AMOUNT] internationally.',
        gallery: [
            { src: '/3D-Images/2-37.jpg.jpeg', alt: 'Modern living room interior render with daylight' },
            { src: '/3D-Images/2-42.jpg.jpeg', alt: 'Hospitality lobby interior 3D render' },
        ],
        related: ['exterior-3d-rendering', '360-virtual-tour', 'interior-design'],
        relatedBlog: ['3d-rendering-for-interior-designers', 'exterior-vs-interior-rendering'],
    },
    {
        slug: '3d-walkthrough-animation',
        name: '3D Walkthrough Animation',
        category: '3D Visualization',
        title: '3D Walkthrough Animation | Cinematic Architectural Walkthroughs',
        description: 'Cinematic 3D walkthrough animations for architecture, real estate marketing & interior showcases. 60fps, 4K delivery. Studio in Amritsar.',
        h1: '3D Walkthrough Animation',
        intro: "A 3D walkthrough is a cinematic animation that flies a virtual camera through your unbuilt project, revealing exterior, entry, lobby and interior spaces in a single 60–180 second narrative. It is the highest-impact pre-sales asset for real estate and the most persuasive client deliverable for architects.",
        secondary: "We deliver 4K (3840 × 2160) walkthroughs at 60 frames per second, with custom camera paths, optional voice-over, royalty-free music and full sound design. Final files are delivered in MP4 (H.264) plus a vertical 9:16 cut for Instagram and YouTube Shorts.",
        types: [
            { name: 'Pre-sales walkthroughs', desc: 'Lobby → amenities → unit interior — the standard for off-plan real estate launches.' },
            { name: 'Client presentation reels', desc: 'Short 30–60 second cuts for design review meetings.' },
            { name: 'Social-first vertical cuts', desc: '9:16 reels for Instagram, TikTok, YouTube Shorts and WhatsApp Status.' },
            { name: 'Aerial fly-throughs', desc: 'Drone-style flights over master plans and townships.' },
            { name: 'Interior cinematic walkthroughs', desc: 'Slow, mood-driven camera moves through finished interiors.' },
        ],
        process: [
            'Brief: scope, duration, music style, voice-over y/n.',
            'Camera path planning — we sketch the route and confirm with you.',
            '3D modeling and material assignment.',
            'Lighting setup, animation, render farm submission.',
            'Post-production: colour grade, music, sound design.',
            'Two revision rounds, then 4K delivery + 9:16 social cut.',
        ],
        software: '3ds Max + V-Ray for photorealism, Lumion for fast turnarounds, Unreal Engine for real-time walkthroughs and VR.',
        turnaround: '10–15 business days per minute of animation. Rush 5–7 days.',
        pricing: 'Starts from ₹[AMOUNT] per minute of animation / $[AMOUNT] internationally.',
        gallery: [],
        related: ['360-virtual-tour', 'exterior-3d-rendering', 'interior-3d-rendering'],
        relatedBlog: ['walkthrough-vs-360-tour', '3d-rendering-real-estate-presales'],
    },
    {
        slug: '360-virtual-tour',
        name: '360° Virtual Tours',
        category: '3D Visualization',
        title: '360° Virtual Tours for Architecture | Interactive VR Walkthroughs',
        description: 'Interactive 360° virtual tours for architecture, real estate & hospitality. Web, mobile & VR headset compatible. Embed on your website.',
        h1: '360° Virtual Tours',
        intro: "A 360° virtual tour lets your client stand inside an unbuilt space, look around in any direction and walk between rooms by clicking hotspots. It works on any web browser, on mobile, and on a VR headset — no app install required.",
        secondary: "We render interactive 360° tours with hotspot navigation between rooms, embedded floor-plan mini-maps and information overlays for materials and dimensions. Tours embed on your website with a single iframe and can be shared as a link, QR code or email embed.",
        types: [
            { name: 'Single-room 360° render', desc: 'One panoramic frame for a hero room — listings, brochures, social posts.' },
            { name: 'Multi-room interactive tour', desc: 'Hotspot-linked tour through an entire property.' },
            { name: 'VR-ready experiences', desc: 'Optimised for Meta Quest, Apple Vision Pro and other headsets.' },
            { name: 'Web embeds & QR codes', desc: 'Embed in your website or Instagram bio, or print a QR for site hoardings.' },
        ],
        process: [
            'Brief: number of scenes, navigation flow, branding.',
            '3D modeling, materials, lighting (same pipeline as still renders).',
            'Cubemap rendering at 8K per face for crisp panoramas.',
            'Hotspot wiring and tour build in our viewer or your preferred platform.',
            'Web embed code + standalone shareable URL delivered.',
        ],
        software: '3ds Max + V-Ray for cubemap rendering, custom WebGL viewer (Three.js) for the embed.',
        turnaround: '7–12 business days for a typical 4–6 scene tour. Rush 3–5 days.',
        pricing: 'Starts from ₹[AMOUNT] per scene / $[AMOUNT] internationally.',
        gallery: [],
        related: ['3d-walkthrough-animation', 'interior-3d-rendering', 'exterior-3d-rendering'],
        relatedBlog: ['walkthrough-vs-360-tour'],
    },
    {
        slug: 'architecture-planning',
        name: 'Architecture Planning',
        category: 'Architecture & Construction',
        title: 'Architecture Planning Services | Site, Floor & Building Design',
        description: 'Functional, future-ready architecture planning — site analysis, floor plans, building-code compliance and sustainable design for residential & commercial projects.',
        h1: 'Architecture Planning',
        intro: "Architecture planning is the design groundwork that turns a piece of land and a brief into a buildable project. We deliver complete planning packages — site analysis, zoning study, floor plans, sections, elevations and code-compliance documentation — for residential, commercial and mixed-use projects.",
        secondary: "Every plan we produce is rendered as a 3D model in parallel, so you can see the finished building before a single brick is laid. Planning and visualisation under one roof means fewer revisions, lower cost and a faster path to construction.",
        types: [
            { name: 'Site analysis & zoning', desc: 'Topography, sun path, wind direction, setbacks and FAR study.' },
            { name: 'Space planning', desc: 'Functional layouts that maximise usable area without sacrificing flow.' },
            { name: 'Building code compliance', desc: 'Plans that pass municipal approval the first time.' },
            { name: 'Sustainable design', desc: 'Passive cooling, daylight, rainwater harvesting and solar-ready roofs.' },
            { name: 'Residential & commercial', desc: 'From single homes to 100k sq ft commercial complexes.' },
        ],
        process: [
            'Site visit or topographical survey review.',
            'Brief workshop and budget alignment.',
            'Concept plans (2–3 options) with 3D massing.',
            'Selected concept developed into full working drawings.',
            'Submission package for municipal approval.',
        ],
        software: 'AutoCAD, Revit, SketchUp for planning; 3ds Max + Lumion for parallel 3D massing.',
        turnaround: 'Concept in 7–14 days; full working drawings 4–8 weeks depending on scale.',
        pricing: 'Starts from ₹[AMOUNT] per sq ft of built-up area. Get a custom quote based on scope.',
        gallery: [],
        related: ['elevation-design', 'interior-design', 'turnkey-construction'],
        relatedBlog: ['what-is-architectural-visualization'],
    },
    {
        slug: 'elevation-design',
        name: 'Elevation Design',
        category: 'Architecture & Construction',
        title: 'Elevation Design Services | Modern Façade & Building Elevations',
        description: 'Distinctive façade and elevation design — modern, contemporary and classical styles — with photorealistic 3D previews before you build.',
        h1: 'Elevation Design',
        intro: "The elevation is your building’s public face — the first thing every visitor, neighbour and prospective buyer sees. A great elevation balances proportion, material, texture and light. We design elevations that are unmistakably yours and visualise every option in photorealistic 3D before you commit.",
        secondary: "We work in modern, contemporary, minimalist, classical, traditional Indian and Mediterranean styles. Every elevation comes with material specifications, finish samples and a 3D rendered preview.",
        types: [
            { name: 'Modern & contemporary façades', desc: 'Clean lines, large glazing, mixed-material palettes.' },
            { name: 'Minimalist elevations', desc: 'Restrained palettes, focus on proportion and light.' },
            { name: 'Classical & traditional', desc: 'Indian, colonial and Mediterranean influences executed with rigour.' },
            { name: 'Mixed-use commercial façades', desc: 'Retail-at-grade with residential or office above.' },
            { name: '3D elevation previews', desc: 'Every option rendered in photoreal 3D so you can choose with certainty.' },
        ],
        process: [
            'Style and budget brief.',
            '3 elevation concepts with mood boards.',
            'Selected concept developed in 3D with material specs.',
            '2 rounds of revisions.',
            'Final drawings + 3D rendered preview.',
        ],
        software: 'AutoCAD, SketchUp, 3ds Max + V-Ray.',
        turnaround: '7–10 business days for concept; 2–3 weeks for full elevation set with renders.',
        pricing: 'Starts from ₹[AMOUNT] per elevation set / $[AMOUNT] internationally.',
        gallery: [],
        related: ['architecture-planning', 'exterior-3d-rendering', 'turnkey-construction'],
        relatedBlog: ['exterior-vs-interior-rendering'],
    },
    {
        slug: 'interior-design',
        name: 'Interior Design',
        category: 'Architecture & Construction',
        title: 'Interior Design Services | Residential, Commercial & Hospitality',
        description: 'Full-service interior design — space planning, material palette, furniture curation and execution for residential, commercial and hospitality projects.',
        h1: 'Interior Design',
        intro: "Interior design is the layer where architecture becomes home. We design interiors for residences, offices, restaurants, retail stores and hotels — from space planning through material palette, furniture curation and on-site execution.",
        secondary: "Every interior we design is visualised in photoreal 3D before procurement, so you see the finished room before any money is spent on furniture or finishes. Surprises are expensive; renders are not.",
        types: [
            { name: 'Residential interiors', desc: 'Apartments, villas and bungalows — turnkey or design-only.' },
            { name: 'Commercial & office', desc: 'Workplace design that signals your brand and supports productivity.' },
            { name: 'Hospitality', desc: 'Restaurants, hotels and resorts with mood-driven design.' },
            { name: 'Retail & showroom', desc: 'Customer journeys engineered around the merchandise.' },
            { name: 'Furniture & joinery design', desc: 'Custom built-ins, wardrobes, kitchens and standalone pieces.' },
        ],
        process: [
            'Brief, lifestyle and budget conversation.',
            'Space planning and 2D layouts.',
            'Material palette and 3D rendered concept.',
            'Two revision rounds.',
            'Procurement and execution (turnkey) or detailed drawings (design-only).',
        ],
        software: 'AutoCAD, SketchUp, 3ds Max + Corona for renders.',
        turnaround: 'Concept in 2–3 weeks; full execution timelines depend on scope.',
        pricing: 'Design-only from ₹[AMOUNT] per sq ft. Turnkey from ₹[AMOUNT] per sq ft.',
        gallery: [],
        related: ['interior-3d-rendering', 'turnkey-construction', 'architecture-planning'],
        relatedBlog: ['3d-rendering-for-interior-designers'],
    },
    {
        slug: 'turnkey-construction',
        name: 'Turnkey Construction Projects',
        category: 'Architecture & Construction',
        title: 'Turnkey Construction Projects | Concept to Handover',
        description: 'End-to-end turnkey construction — design, approvals, procurement, construction, finishes and handover under one accountable contract.',
        h1: 'Turnkey Construction Projects',
        intro: "Turnkey means you hand us a piece of land and a brief and we hand you back keys to a finished building. Architecture, structural design, MEP, approvals, procurement, construction, finishes, interiors and snagging — all under one contract, one timeline and one point of accountability.",
        secondary: "Turnkey is the right model when you do not want to manage three architects, four contractors and seven vendors. We typically run residential bungalows, small commercial buildings and boutique hospitality projects on this model.",
        types: [
            { name: 'Residential turnkey', desc: 'Single-family bungalows and villas.' },
            { name: 'Boutique commercial', desc: 'Showrooms, clinics and small offices.' },
            { name: 'Hospitality fitouts', desc: 'Restaurants, cafes and boutique hotels.' },
            { name: 'Renovation turnkey', desc: 'Strip-back-to-shell renovations of existing properties.' },
        ],
        process: [
            'Site visit, brief workshop, budget alignment.',
            'Concept design + 3D rendered preview.',
            'Working drawings, MEP and structural design.',
            'Approvals and permits.',
            'Procurement, construction and finishes.',
            'Snagging, handover and warranty.',
        ],
        software: 'AutoCAD, Revit, MS Project for scheduling, 3ds Max for 3D previews.',
        turnaround: 'Bungalow: 9–14 months. Commercial fitout: 3–6 months. Renovation: 4–8 months.',
        pricing: 'Quoted per project after site visit. Typically ₹[AMOUNT]–₹[AMOUNT] per sq ft built-up.',
        gallery: [],
        related: ['architecture-planning', 'elevation-design', 'interior-design'],
        relatedBlog: [],
    },
];

export const SERVICE_BY_SLUG = Object.fromEntries(SERVICES.map((s) => [s.slug, s]));

export const SERVICE_CATEGORIES = [
    { name: '3D Visualization', services: SERVICES.filter((s) => s.category === '3D Visualization') },
    { name: 'Architecture & Construction', services: SERVICES.filter((s) => s.category === 'Architecture & Construction') },
];
